// Mocks generated by Mockito 5.3.2 from annotations
// in inovola_tech_task/test/modules/courses/presentation_layer/managers/courses_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:inovola_tech_task/modules/courses/data_layer/services_impl/courses_service_impl.dart'
    as _i2;
import 'package:inovola_tech_task/modules/courses/domain_layer/entities/course_details_entity.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CoursesServiceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoursesServiceImpl extends _i1.Mock
    implements _i2.CoursesServiceImpl {
  MockCoursesServiceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.CourseDetailsEntity?> getCourseDetails() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCourseDetails,
          [],
        ),
        returnValue: _i3.Future<_i4.CourseDetailsEntity?>.value(),
      ) as _i3.Future<_i4.CourseDetailsEntity?>);
}
